services:
  - type: web
    name: webapp
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app_postgres:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: ENV
        value: prod
      - key: SESSION_SECRET
        generateValue: true
      - key: APP_PASSWORD
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: webapp-db
          property: connectionString

databases:
  - name: webapp-db
    plan: free
